#!/bin/bash

# Script to help set up NPM authentication for publishing

echo "🔐 NPM Authentication Setup for Claude Gate"
echo "=========================================="
echo ""
echo "This script will help you set up NPM authentication for publishing."
echo ""
echo "Prerequisites:"
echo "1. Create an npm account at https://www.npmjs.com/signup"
echo "2. Enable 2FA for publishing (required for security)"
echo "3. Create an access token at https://www.npmjs.com/settings/~/tokens"
echo "   - Choose 'Automation' token type"
echo "   - Select 'Publish' permission"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "Setting up GitHub Secrets"
echo "========================"
echo ""
echo "You need to add the NPM token as a GitHub secret:"
echo ""
echo "1. Go to: https://github.com/ml0-1337/claude-gate/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Name: NPM_TOKEN"
echo "4. Value: [paste your npm token]"
echo ""
echo "The GitHub Actions workflow will use this token to publish packages."
echo ""

echo "Local Publishing Setup (Optional)"
echo "================================"
echo ""
echo "To publish manually from your local machine:"
echo ""
echo "1. Login to npm:"
echo "   npm login"
echo ""
echo "2. Verify you're logged in:"
echo "   npm whoami"
echo ""
echo "3. To publish (after building):"
echo "   cd npm && npm publish --access public"
echo ""

echo "Publishing Checklist"
echo "==================="
echo ""
echo "Before publishing:"
echo "[ ] Update version in cmd/claude-gate/main.go"
echo "[ ] Update version in npm/package.json"
echo "[ ] Update version in all platform packages"
echo "[ ] Run tests: make test"
echo "[ ] Build snapshot: make snapshot"
echo "[ ] Test npm locally: make npm-test"
echo "[ ] Commit all changes"
echo "[ ] Create and push tag: git tag v0.1.0 && git push origin v0.1.0"
echo ""
echo "The GitHub Actions workflow will handle the rest!"